version: '3'

services:
  rent_database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=rent_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
